### ISSUE TITLE
Execution RecurringJobScheduler is in the Failed state now due to an exception

### ISSUE THREAD

**Issue by mudasar** [imranmomin/Hangfire.AzureDocumentDB#61]
Hello there,
I am facing this issue when running multiple servers with the same database. there are some recurring jobs which are stuck to a single server that was turned off. Is there a direct way to trigger these jobs manually? 
Also, any solution to the following issue?

`Execution RecurringJobScheduler is in the Failed state now due to an exception, execution will be retried no more than in 00:00:16
System.ArgumentException: An item with the same key has already been added. Key: LastExecution`

**Comment by mudasar** [comment]
complete error stack is here 
`[15:05:48 ERR] HTTP GET /hangfire/recurring responded 500 in 1451.9199 ms
System.ArgumentException: An item with the same key has already been added. Key: LastExecution
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Hangfire.Azure.CosmosDbConnection.GetAllEntriesFromHash(String key)
   at Hangfire.Storage.StorageConnectionExtensions.GetRecurringJobDtos(IStorageConnection connection, IEnumerable`1 ids)
   at Hangfire.Storage.StorageConnectionExtensions.GetRecurringJobs(JobStorageConnection connection, Int32 startingFrom, Int32 endingAt)
   at Hangfire.Dashboard.Pages.RecurringJobsPage.Execute()
   at Hangfire.Dashboard.RazorPage.TransformText(String body)
   at Hangfire.Dashboard.RazorPage.ToString()
   at Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
   at Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)`

**Comment by imranmomin** [comment]
`An item with the same key has already been added. Key: LastExecution` 

What you can do is find the duplicate Hash entry for this recurring job and delete the older document. 

`select * from c where type = 6 and key = 'recurring-job-id'`

**Comment by mudasar** [comment]
Hi, @imranmomin  thanks for your reply. I did fix it by going through the cosmos DB for recurring jobs that were a lot. This happens when you try to join an already running job queue server.

**Comment by mudasar** [comment]
Is there a way we can avoid getting into this position at all ?

**Comment by dioptre** [comment]
This broke for us too.
